travis:
  secure:
    BINSTAR_TOKEN: tnuIwGHf5mYFElEAIXzFwVGZYBP70hU6qZmaa7RQpVsPs/Y1yH0qgT9AVIOI6i7fetQMvaH63zClKLrx4jKj8KGe2gombP1yXAtfMM/Xy3zWYLkILtoEMXnpnKow1tJzSUdg4gwc8K0dBEdyzRohztR/Py9+JrcjFkYGhF5ZBfx6ScfgB9KIjlmX5zwamKAqdd835y4StVMzVGTcDI8+EJF4054t0Xbc8PRcnQZmy/JtmfXMw3TJ1YHhlweCKced6Hwo/JUXG5zcp17hCsRg+IpP4cEsvovnrkDSWfXQJykDjQRrxrEbziFP5dxWHF+jrkDpAMLfh2d2UJA5XDrksO8mflwsZW/CN8SEU9bGMXo/I6mFnWrzu8byc6hSTmorSXV5n64Ee/LI04q74YAvZezhyN7VvUZDndE+d0PD7/3EasjeLYsIwOI9xwQJBf85eWbmDA8Ri0xF7unNDx9korebUwIiO5Fo0x2IgmyZVX7isaOLPv1ZCuhQgtg7g3eom5fadtJQHtvFttg3RzUaUbUQE/+VHgPczhWDWlVBZHqw6i45GZQGw1Ho85j6b72fzkBEPH9+WLpp5JGfhQ/FDF5nnR+o+hi9WfG7VAy2loeZDUrYup+wbEhkFRFsWz/+L3pd8UCAaMTZOgKUFGdM5iTLwA9ZOonfzcGr1q1oL+I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
